mixed-port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: false
bind-address: '*'
ipv6: false
mode: rule
log-level: info
external-controller: '127.0.0.1:9090'
secret: ''
#dns:
#  enable: false
#  listen: 0.0.0.0:53 
#  ipv6: false
#  default-nameserver:
#    - 1.2.4.8
#    - 223.5.5.5
#    - 119.29.29.29    
#  nameserver:
#    - 1.2.4.8
#    - 119.29.29.29
#    - 223.5.5.5
#    - tls://dns.rubyfish.cn:853
#  fallback:
#    - 223.5.5.5
#    - tls://1.0.0.1:853
#    - tls://dns.google:853
# Will be ignored after profile selection
proxies:
  - name: "socks"
    type: socks5
    server: 127.0.0.1
    port: 1080
    
  - name: "http"
    type: http
    server: 127.0.0.1
    port: 1080
    
  - name: "ss"
    type: ss
    server: xxx.xxx.com
    port: 222
    cipher: chacha20-ietf-poly1305
    password: "password"
    udp: true
    
  - name: "ssr"
    type: ssr
    server: xxx.xxx.com
    port: 3396
    cipher: chacha20-ietf
    password: "password"
    obfs: tls1.2_ticket_auth
    protocol: auth_sha1_v4
    obfs-param: download.microsoft.com
    protocol-param: "31057:8wPxj2"
    udp: true
    
  - name: "vmess"
    type: vmess
    server: xxx.xxx.com
    port: 443
    uuid: 998272ec-6486-43ab-a450-86e6964be97f
    alterId: 64
    cipher: auto
    tls: true
    network: ws
    ws-path: /
    Host: xxx.xxx.com

  - name: "trojan"
    type: trojan
    server: xxx.xxx.com
    port: 443
    password: password
    sni: xxx.xxx.com
    alpn:
      - h2
      - http/1.1
    skip-cert-verify: true
    
  - name: "snell"
    type: snell
    server: xxx.xxx.com
    port: 9443
    psk: password
    #version: 2
    obfs-opts:
      mode: tls # or http
      host: xxx.xxx.com
      
proxy-groups:
  - name: ✈️ 墙外网站
    type: select
    proxies:
      - "负载均衡"
      #- ♻️ 自动选择
      - "socks"
      - "http"
      - "ss"
      - "ssr"
      - "vmess"
      - "trojan"
      - "snell"
      - DIRECT
  - name: 🐟 其他网站
    type: select
    proxies:
      - DIRECT
      - ✈️ 墙外网站
  - name: 🎥 NETFLIX
    type: select
    proxies:
      - "socks"
      - "http"
      - "ss"
      - "ssr"
      - "vmess"
      - "trojan"
      - "snell"
      - DIRECT      
  - name: 🚫 以下不用动
    type: select
    proxies:
      - DIRECT
  - name: 🛑 广告拦截
    type: select
    proxies:
      - DIRECT
      - REJECT
  - name: Ⓜ️ 微软苹果
    type: select
    proxies:
      - DIRECT
      - ✈️ 墙外网站
  - name: 🌍 国外媒体
    type: select
    proxies:
      - ✈️ 墙外网站
      - DIRECT
  #- name: ♻️ 自动选择
  #  type: url-test
  #  url: http://www.gstatic.com/generate_204
  #  interval: 500
  #  proxies:
  #    - "socks"
  #    - "http"
  #    - "ss"
  #    - "ssr"
  #    - "vmess"
  #    - "trojan"
  #    - "snell"
  - name: "负载均衡"
    type: load-balance
    proxies:
      - "socks"
      - "http"
      - "ss"
      - "ssr"
      - "vmess"
      - "trojan"
      - "snell"
    url: 'http://www.gstatic.com/generate_204'
    interval: 500      
rule-providers:
  Apple:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/qist/v2ray/main/clash/Ruleset/Apple.yaml
    interval: 86400
    path: ./Apple.yaml    
  Foreignmedia:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/qist/v2ray/main/clash/Ruleset/Foreignmedia.yaml
    interval: 86400    
    path: ./Foreignmedia.yaml
  Netflix:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/qist/v2ray/main/clash/Ruleset/Netflix.yaml
    interval: 86400    
    path: ./Netflix.yaml
  Reject:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/qist/v2ray/main/clash/Ruleset/Reject.yaml
    interval: 86400    
    path: ./Reject.yaml
  Reject1:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/qist/v2ray/main/clash/Ruleset/Reject1.yaml
    interval: 86400    
    path: ./Reject1.yaml    
  IpDirect:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/qist/v2ray/main/clash/Ruleset/IpDirect.yaml
    interval: 86400    
    path: ./IpDirect.yaml
  Proxy:
    type: http
    url: https://raw.githubusercontent.com/qist/v2ray/main/clash/Ruleset/Proxy.yaml
    interval: 86400    
    behavior: classical
    path: ./Proxy.yaml
  ITdev:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/qist/v2ray/main/clash/Ruleset/ITdev.yaml
    interval: 86400    
    path: ./ITdev.yaml
  Chinao:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/qist/v2ray/main/clash/Ruleset/China-o.yaml
    interval: 86400    
    path: ./China-o.yaml
  Chinat:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/qist/v2ray/main/clash/Ruleset/China-t.yaml
    interval: 86400    
    path: ./China-t.yaml
  Chinas:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/qist/v2ray/main/clash/Ruleset/China-s.yaml
    interval: 86400    
    path: ./China-s.yaml    
# 规则
rules:
  - RULE-SET,Apple,Ⓜ️ 微软苹果
  - RULE-SET,Foreignmedia,🌍 国外媒体
  - RULE-SET,Netflix,🎥 NETFLIX
  - RULE-SET,Reject,🛑 广告拦截
  - RULE-SET,Reject1,🛑 广告拦截
  - RULE-SET,Proxy,✈️ 墙外网站
  - RULE-SET,ITdev,✈️ 墙外网站
  - RULE-SET,IpDirect,DIRECT
  - RULE-SET,Chinao,DIRECT
  - RULE-SET,Chinat,DIRECT
  - RULE-SET,Chinas,DIRECT  
  - DOMAIN-SUFFIX,smtp,DIRECT
  - DOMAIN-KEYWORD,aria2,DIRECT
  - GEOIP,CN,DIRECT
  #- GEOIP,AE,✈️ 墙外网站
  #- GEOIP,AU,✈️ 墙外网站
  #- GEOIP,BR,✈️ 墙外网站
  #- GEOIP,CA,✈️ 墙外网站
  #- GEOIP,DE,✈️ 墙外网站
  #- GEOIP,DK,✈️ 墙外网站
  #- GEOIP,ES,✈️ 墙外网站
  #- GEOIP,FI,✈️ 墙外网站
  #- GEOIP,FR,✈️ 墙外网站
  #- GEOIP,GB,✈️ 墙外网站
  #- GEOIP,GR,✈️ 墙外网站
  #- GEOIP,HK,✈️ 墙外网站
  #- GEOIP,ID,✈️ 墙外网站
  #- GEOIP,IL,✈️ 墙外网站
  #- GEOIP,IN,✈️ 墙外网站
  #- GEOIP,IQ,✈️ 墙外网站
  #- GEOIP,IR,✈️ 墙外网站
  #- GEOIP,IT,✈️ 墙外网站
  #- GEOIP,JP,✈️ 墙外网站
  #- GEOIP,KR,✈️ 墙外网站
  #- GEOIP,MO,✈️ 墙外网站
  #- GEOIP,MY,✈️ 墙外网站
  #- GEOIP,NL,✈️ 墙外网站
  #- GEOIP,NO,✈️ 墙外网站
  #- GEOIP,NZ,✈️ 墙外网站
  #- GEOIP,PH,✈️ 墙外网站
  #- GEOIP,RU,✈️ 墙外网站
  #- GEOIP,SA,✈️ 墙外网站
  #- GEOIP,SG,✈️ 墙外网站
  #- GEOIP,TH,✈️ 墙外网站
  #- GEOIP,TR,✈️ 墙外网站
  #- GEOIP,TW,✈️ 墙外网站
  #- GEOIP,US,✈️ 墙外网站
  #- GEOIP,VN,✈️ 墙外网站
  - MATCH,🐟 其他网站
